// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuQCqAfs4wBLpEK9gWGsUtG4FrflLK21M',
    appId: '1:75932651180:web:f00fc75f21852a9c9dd909',
    messagingSenderId: '75932651180',
    projectId: 'audiobook-maker-fdc9d',
    authDomain: 'audiobook-maker-fdc9d.firebaseapp.com',
    storageBucket: 'audiobook-maker-fdc9d.firebasestorage.app',
    measurementId: 'G-B76NY0Q8M6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJk0Tx9LReP4ySS3MBECTePmHZmlQG0Yw',
    appId: '1:75932651180:android:283291a84c4c5cf49dd909',
    messagingSenderId: '75932651180',
    projectId: 'audiobook-maker-fdc9d',
    storageBucket: 'audiobook-maker-fdc9d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAP2eoy6NLoU8Le5Zbjru7LxN_FXbH49k0',
    appId: '1:75932651180:ios:7de8c1c91b72d6c59dd909',
    messagingSenderId: '75932651180',
    projectId: 'audiobook-maker-fdc9d',
    storageBucket: 'audiobook-maker-fdc9d.firebasestorage.app',
    iosBundleId: 'com.example.audiobookMaker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAP2eoy6NLoU8Le5Zbjru7LxN_FXbH49k0',
    appId: '1:75932651180:ios:7de8c1c91b72d6c59dd909',
    messagingSenderId: '75932651180',
    projectId: 'audiobook-maker-fdc9d',
    storageBucket: 'audiobook-maker-fdc9d.firebasestorage.app',
    iosBundleId: 'com.example.audiobookMaker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuQCqAfs4wBLpEK9gWGsUtG4FrflLK21M',
    appId: '1:75932651180:web:8c1117550a69ab6a9dd909',
    messagingSenderId: '75932651180',
    projectId: 'audiobook-maker-fdc9d',
    authDomain: 'audiobook-maker-fdc9d.firebaseapp.com',
    storageBucket: 'audiobook-maker-fdc9d.firebasestorage.app',
    measurementId: 'G-0QPJ1MGPFZ',
  );
}
